### ISSUE TITLE
On Tuesday the 2nd, change repo for submitting proposals to something more official than test-issues

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/commons-config-backend#43]
currently proposals are made to https://github.com/CommonsBuild/test-issues-config-dashboard/

we should change this to a more permanent repo for legitimate proposals

**Comment by GriffGreen** [comment]
commons-config-proposals

**Comment by divine-comedian** [comment]
https://github.com/CommonsBuild/commons-config-proposals/issues
