### ISSUE TITLE
Effective Supply is 1.5 mil... but it says tokens needed to pass is 3 mil... it should say not possible

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/commons-config-backend#52]
![Screen Shot 2021-10-25 at 2 21 46 PM](https://user-images.githubusercontent.com/14945613/138765245-e22fdc4f-bfe5-4217-8dab-402bb4a60306.png)

See scenario 3... there should be a check to confirm that if its asking for more tokens than the effective supply then it's not possible

**Comment by GriffGreen** [comment]
<img width="746" alt="Screen Shot 2021-11-23 at 7 20 56 AM" src="https://user-images.githubusercontent.com/14945613/143031600-2872e38b-df5c-4881-8c4d-d68339fda740.png">

Still happening

**Comment by marthendalnunes** [comment]
@GriffGreen fixed, one dimension of the conviction voting period was not being considered into the "not possible" cap
![image](https://user-images.githubusercontent.com/18421017/144235529-20a4645d-ff69-45bb-9d0f-7e0ac606d4af.png)
![image](https://user-images.githubusercontent.com/18421017/144235559-5737a54a-b007-4af2-98ae-a9640731a7c9.png)
